DRAW = "DRAW"
WIN = "WIN"
LOSE = "LOSE"

MODE_NORMAL = 'NORMAL'
MODE_HARD = 'HARD'
MODES = {'1': MODE_NORMAL,
         '2': MODE_HARD}

START = '1'
SCORES = '2'
EXIT = '3'

ENEMY_LIVES = 5
ENEMY_LIVES_FOR_MODE_HARD = 6
PLAYER_LIVES = 5
PLAYER_LIVES_FOR_MODE_HARD = 3
POINTS_FOR_FIGHT = 1
POINTS_FOR_FIGHT_FOR_MODE_HARD = 2
POINTS_FOR_KILLING = 5
POINTS_FOR_KILLINGS_FOR_MODE_HARD = 10
MAX_RECORDS_NAMBER = 10

SCORE_FILE = 'scores.txt'

PAPER = 'Paper'
STONE = 'Stone'
SCISSORS = 'Scissors'

ALLOWED_ATTACKS = {
    '1': PAPER,
    '2': STONE,
    '3': SCISSORS
}

ATTACK_PAIRS_OUTCOME = {
    (PAPER, PAPER): DRAW,
    (PAPER, STONE): WIN,
    (PAPER, SCISSORS): LOSE,
}